sudo: false

language: c
compiler:
  - gcc
  - clang
os:
  - linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

# before install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
# install:
#   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script:
  - gcc ex.c main.c -lm
  - cmake CMakeLists.txt && make
  - ./runTests